In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich)

In [ ]:
np.dot(a,b)

In [ ]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a)
np.linalg.norm(a, 2)

In [ ]:
a = np.array([1,2,-3])
np.linalg.norm(a,1)

In [ ]:
def chuan(v,k):
 tong = 0
 for i in range(len(v)):
  tong = tong + abs(v[i]**k)
 ketqua = math.pow(tong, 1.0/k)
 return ketqua

In [ ]:
import math
import numpy as np
a = np.array([1,2,-3])

In [ ]:
chuan(a, 1)
np.linalg.norm(a,1)

In [ ]:
chuan(a, 2)
np.linalg.norm(a,2)

In [ ]:
chuan(a, 3)
np.linalg.norm(a,3)

In [ ]:
chuan(a, 1000)
np.linalg.norm(a,1000)

In [ ]:
from scipy import linalg
linalg.norm(a)

In [ ]:
linalg.norm(a, 100)

In [ ]:
linalg.norm(a, 1000)

In [ ]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)

[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [ ]:
v = (1.0/m)*MT.dot(mi)
print(v)

In [ ]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

In [ ]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)

In [ ]:
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print (sympy.pretty(nghiem))

In [ ]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [ ]:
A.dot(P)
P.dot(D)
P @ (D ** 1000) @ P1
print (D **2)

In [ ]:
import numpy as np
a = np.array([1,2,3])
mag = np.sqrt(a.dot(a))
mag = np.sqrt(a @ a )
mag = np.sqrt(np.inner(a,a))
mag = lambda x : math.sqrt(sum(i** 2 for i in x))
mag(a)

In [ ]:
import numpy as np
a=np.array(list(map(float,input("Nhập vector a (cách nhau dấu cách): ").split())))
b=np.array(list(map(float,input("Nhập vector b (cách nhau dấu cách): ").split())))
c=a-b
d=np.linalg.norm(c)
print(f"\n1) Khoảng cách ||a-b||={d:.6f}")
e=np.dot(a, b)
na=np.linalg.norm(a)
nb=np.linalg.norm(b)
cosθ=np.clip(e/(na*nb),-1.0,1.0)
θ_rad=np.arccos(cosθ)
θ_deg=np.degrees(θ_rad)
print(f"2) Góc θ: {θ_rad:.6f} rad≃{θ_deg:.2f}°")
f=(e/np.dot(b,b))*b
print(f"3) Chiếu trực giao p={f}")