Bài tập 1

In [ ]:
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)

[ 18 -11   9  -8]


In [ ]:
x=0.5*(2*u-v-3*w)
print (x)

[ 9.  -5.5  4.5 -4. ]


In [ ]:
Bài toán 2

In [ ]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

[ 1. -2. -1.]


Bài toán 3

In [ ]:
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
try:
     LA.inv(A)
except Exception as e:
     print(e)
try:
     LA.inv(B)
except Exception as e:
     print(e)
try:
     print(LA.inv(A + B))
except Exception as e:
     print(e)

Singular matrix
Singular matrix
[[1. 0.]
 [0. 1.]]


In [ ]:
  import numpy as np
from numpy import linalg as LA
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
try:
    print("det(A):", LA.det(A))
except Exception as e:
    print("Lỗi khi tính định thức A:", e)
try:
    print("det(B):", LA.det(B))
except Exception as e:
    print("Lỗi khi tính định thức B:", e)
try:
    print("det(A + B):", LA.det(A + B))
except Exception as e:
    print("Lỗi khi tính định thức A + B:", e)

det(A): 0.0
det(B): 0.0
det(A + B): 1.0


Bài toán 4

In [ ]:
import math
import sympy as sp
x, y = sp.symbols('x y') # khai báo 2 biến x và y
A = sp.Matrix([[x, y],[y, x]]) # lưu ý: kiểu ma trận của sympy là ‘Matrix’ (viết hoa)
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
print(A1.T)
print((A1+A2).T)
print(((A1+A2).T).equals(A1+A2))
c=sp.symbols('c')
print(c*A)
print(((c*A).T).equals(c*A))

Matrix([[x1, y1], [y1, x1]])
Matrix([[x1 + x2, y1 + y2], [y1 + y2, x1 + x2]])
True
Matrix([[c*x, c*y], [c*y, c*x]])
True


Bài toán 5

In [ ]:
import numpy as np
V = np.column_stack([
    [1, 2, 3],   # v1
    [0, 1, 2],   # v2
    [-1, 0, 1]   # v3
])

#a Kiểm tra (1,1,1)
w1 = np.array([1, 1, 1])
try:
    c = np.linalg.solve(V, w1)
    print("Vector w1 là tổ hợp tuyến tính của v1, v2, v3 với hệ số:", c)
except np.linalg.LinAlgError as e:
    print("Vector w1 KHÔNG là tổ hợp tuyến tính:", e)

#b Kiểm tra(1, -2, 2)
w2 = np.array([1, -2, 2])
try:
    c = np.linalg.solve(V, w2)
    print("Vector w2 là tổ hợp tuyến tính của v1, v2, v3 với hệ số:", c)
except np.linalg.LinAlgError as e:
    print("Vector w2 KHÔNG là tổ hợp tuyến tính:", e)

Vector w1 là tổ hợp tuyến tính của v1, v2, v3 với hệ số: [ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]
Vector w2 là tổ hợp tuyến tính của v1, v2, v3 với hệ số: [ 3.15251974e+16 -6.30503948e+16  3.15251974e+16]


Bài toán 6

In [ ]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
tong=sp.solve([c1 - 2*c3, 2*c1 + c2, 3*c1 + 2*c2 + c3], [c1, c2, c3])
print(tong)

{c1: 0, c2: 0, c3: 0}


Bài toán 7

In [ ]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
c=sp.solve([c1+c2-u1,c1-c2-u2])
print(c)
u1 = 0
u2 = 0
u = sp.solve([c1+c2-u1,c1-c2-u2])
print(u)

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}
{c1: 0, c2: 0}


In [ ]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [ ]:
import numpy as np
P=np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta=np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],[0.0, 2.0]])
P_caub=(P.T@matran_biendoi+vecdelta).T
print(P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [ ]:
import sympy as sp
from sympy import lambdify
14
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c') # khai báo thêm 3 biến a, b, c giả định X = (a, b, c)
d, e, f = sp.symbols('d e f') # khai báo thêm 3 biến d, e, f giả định Y = (e, d, f)
print(f1(a, b, c))
print(f1(d, e, f))
print(f1(a+d, b+e, c+f))
print(f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f))
print((f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f)) )

a - b + c
d - e + f
a - b + c + d - e + f
True
True


In [ ]:
q = sp.symbols('q')
print((q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand()) )

True


In [ ]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
print((q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand()))

True


In [ ]:
import numpy as np
u1 = np.array([1, 2])
u2 = np.array([3, 5])
target = np.array([4, 5])
A = np.column_stack((u1, u2))
alpha_beta = np.linalg.solve(A, target)
alpha, beta = alpha_beta
print(f"alpha = {alpha}, beta = {beta}")
f_u1 = np.array([1, 1, 2])
f_u2 = np.array([4, 2, 1])
f_u3 = alpha * f_u1 + beta * f_u2
print("f(4,5) =", f_u3)

alpha = -5.0, beta = 3.0
f(4,5) = [ 7.  1. -7.]


In [ ]:
import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])

{a: -5*x + 3*y, b: 2*x - y}

In [ ]:
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)

[a + 4*b a + 2*b 2*a + b]


In [ ]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print (fu)

[3*x - y -x + y -8*x + 5*y]


In [ ]:
x, y = sp.symbols('x y')
f = sp.Matrix([3*x - y, -x + y, -8*x + 5*y])
print(f)

Matrix([[3*x - y], [-x + y], [-8*x + 5*y]])


In [ ]:
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

{x1: 2*x3, x2: -x3}

In [ ]:
import numpy as np
def f(x, y):
    return np.array([x - y, x])
B=[np.array([1,-1]),np.array([1,0])]
F=[np.array([1,2]),np.array([1,3])]
def coordinates_in_basis(v, basis):
    A=np.column_stack(basis)
    coeffs=np.linalg.solve(A, v)
    return coeffs
A_columns=[coordinates_in_basis(f(*u),F)for u in B]
A = np.column_stack(A_columns)
print("Ma trận của ánh xạ tuyến tính f trong cặp cơ sở {B, F} là:")
print(A)

Ma trận của ánh xạ tuyến tính f trong cặp cơ sở {B, F} là:
[[ 5.  2.]
 [-3. -1.]]


In [ ]:
import numpy as np
import math
from scipy.linalg import orth
B = np.array([[1.0/math.sqrt(2), 1.0/math.sqrt(2)],
              [-1.0/math.sqrt(2), 1.0/math.sqrt(2)]])
Q = orth(B)
print(Q)

[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([
    [1.0 / math.sqrt(2), 1.0 / math.sqrt(2)],
    [-1.0 / math.sqrt(2), 1.0 / math.sqrt(2)]])
print(B)
print(LA.orth(B))
expected = np.array([
    [-0.70710678, 0.70710678],
    [ 0.70710678, 0.70710678]])
print(expected)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
Q = np.array([[4, -1, 0], [1, 3, -2], [0, 1, 2]])
print(Q)
Gia_tri_rieng, Vector_rieng = np.linalg.eig(Q)
print(Gia_tri_rieng)
Vector_rieng_chuan_hoa = Vector_rieng / np.linalg.norm(Vector_rieng, axis=0)
print(Vector_rieng_chuan_hoa)

BÀI TẬP CHƯƠNG

In [1]:
# CÂU 1 - Kiểm tra ảnh xạ có phải tuyến tính không
# g(x, y, z) = (x + y, z + 2, 0)
from sympy import symbols, Matrix

x, y, z = symbols('x y z')

gu = Matrix([x + y, z + 2, 0])
print(gu)

gv = Matrix([2*x + 2*y, 2*z + 4, 0])
print(gv)

g_u_v = Matrix([(x + x + y + y), (z + z + 2 + 2), 0])
print(g_u_v)

la_tuyen_tinh = False
print("Câu 1: Tuyến tính:", la_tuyen_tinh)

Matrix([[x + y], [z + 2], [0]])
Matrix([[2*x + 2*y], [2*z + 4], [0]])
Matrix([[2*x + 2*y], [2*z + 4], [0]])
Câu 1: Tuyến tính: False


In [2]:
# CÂU 2 - Biến đổi: x -> y, y -> x - y
import numpy as np
P = np.array([[0, 1], [1, -1]])
F = np.array([[1, 2, 3], [4, 5, 6]])  # ví dụ tập điểm
bien_doi_F = P @ F
print("Câu 2: Biến đổi:", bien_doi_F)

Câu 2: Biến đổi: [[ 4  5  6]
 [-3 -3 -3]]


In [4]:
# CÂU 3 - Chứng minh T là ánh xạ tuyến tính
# T(v1, v2) = (v1 − v2, v1 + 2*v2)
import sympy as sp
v1, v2 = sp.symbols('v1 v2')
a, b = sp.symbols('a b')
u1, u2 = sp.symbols('u1 u2')
v1a, v2a = sp.symbols('v1a v2a')
Tu = (u1 - u2, u1 + 2*u2)
Tv = (v1a - v2a, v1a + 2*v2a)
print("Tu =", Tu)
print("Tv =", Tv)
T_ab_uv = (a*u1 + b*v1a - (a*u2 + b*v2a), a*u1 + b*v1a + 2*(a*u2 + b*v2a))
print("T(a*u + b*v) =", T_ab_uv)
T_linear_comb = (a*Tu[0] + b*Tv[0], a*Tu[1] + b*Tv[1])
print("a*T(u) + b*T(v) =", T_linear_comb)
kiem_tra_T = sp.simplify(sp.Matrix(T_ab_uv) - sp.Matrix(T_linear_comb)) == sp.Matrix([0, 0])
print("Câu 3: T là ánh xạ tuyến tính:", kiem_tra_T)

Tu = (u1 - u2, u1 + 2*u2)
Tv = (v1a - v2a, v1a + 2*v2a)
T(a*u + b*v) = (a*u1 - a*u2 + b*v1a - b*v2a, a*u1 + 2*a*u2 + b*v1a + 2*b*v2a)
a*T(u) + b*T(v) = (a*(u1 - u2) + b*(v1a - v2a), a*(u1 + 2*u2) + b*(v1a + 2*v2a))
Câu 3: T là ánh xạ tuyến tính: True


In [7]:
# CÂU 4 - Quadratic form: X^T A X + [d e] X + f
# Phương trình ellipse: 13x² − 10xy + 13y² − 72 = 0
A = np.array([[13, -5], [-5, 13]])
from numpy import linalg as LA
import math
Gia_tri_rieng, Vecto_rieng = LA.eig(A)
P = Vecto_rieng
A_cheo = P.T @ A @ P
print(A_cheo)
kiem_tra_truc_giao = np.allclose(P.T @ P, np.eye(2))
print("Kiểm tra trực giao:", kiem_tra_truc_giao)
theta = math.atan2(P[1, 0], P[0, 0]) * 180 / math.pi
print("Góc xoay (độ):", round(theta, 2))
print("Câu 4: Giá trị riêng:", Gia_tri_rieng)

[[ 1.8000000e+01  0.0000000e+00]
 [-8.8817842e-16  8.0000000e+00]]
Kiểm tra trực giao: True
Góc xoay (độ): -45.0
Câu 4: Giá trị riêng: [18.  8.]
