In [ ]:
import numpy as np
D = np.array([[1,2],[3,4]])
E = np.empty_like(D) # Define E before using it
np.copyto(E, D)
E = np.array([[1,2],[3,5]])
np.copyto(E, D)
print(E)

[[1 2]
 [3 4]]


In [ ]:
B = np.matrix("[1 2 3; 4 5 6]")
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.matrix([[x,y],[1, 2]] )
print (C)

In [ ]:
#Lỗi
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [ ]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # sinh viên ghi nhận kết quả
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [2]:
from numpy import matlib
G = matlib.identity(5)
print (G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-0.17567282 -2.36449355]
 [-0.30185257 -1.2262693 ]
 [-0.61204444  0.4741424 ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
H = matlib.randn(3,2)
print(H)

In [ ]:
K = matlib.zeros([4,4])
print(K)

In [3]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.asmatrix([[1,2],[3,4]])
for i in range(len(c)):
 ci = np.asmatrix([[1,1],[1,0]])
 ci[0, 0] = c[i]
 if (i==0):
  M = ci
 else:
  M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


Bài 3

In [ ]:
import numpy as np
X = np.array([[1,1], [1,2], [1,3], [1,4], [1,5]])
Y = np.array([[1], [2], [4], [4], [6]])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
A = A1.dot(A2)
print(A)

Bài tập chương

Thực hành

In [4]:
import numpy as np
def bpcuctieu(x, y):
    o1 = [1.0] * len(x)
    X = np.vstack([o1, x]).T
    y = np.array(y)
    XT_X = np.dot(X.T, X)
    XT_X_inv = np.linalg.inv(XT_X)
    XT_y = np.dot(X.T, y)
    A = np.dot(XT_X_inv, XT_y)
    return A
x = [0, 1, 2, 3, 4]
y = [10.0, 8, 7, 5, 2]
kq = bpcuctieu(x, y)
print(f"Phương trình tuyến tính: y = {kq[0]:.1f} + {kq[1]:.1f}x")

Phương trình tuyến tính: y = 10.2 + -1.9x
