Câu 1

In [6]:
#Ma trận
import numpy as np
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])
print("Ma trận A:", A)
print("Ma trận B:", B)
print("Ma trận C:", C)

Ma trận A: [ 2 -1  3  0]
Ma trận B: [ 1  4 -2  5]
Ma trận C: [[ 1  2 -1]
 [ 0  3  4]
 [ 2 -1  0]]


a) Phép toán cơ bản trên vector và ma trận

In [9]:
tong=A+B
tru=(3*A)-(2*B)
print(tong)
print(tru)

[3 3 1 5]
[  4 -11  13 -10]


B)Tính tích vô hướng A · B và góc giữa hai vector (tính bằng độ, làm tròn đến 3 chữ số thập phân).

In [10]:
Tich_vo_huong = np.dot(A, B)
print("Tích vô hướng của A và B:", Tich_vo_huong)
Do_dai_A = np.linalg.norm(A)
print("Do_dai_A")
Do_dai_B = np.linalg.norm(B)
print("Do_dai_B")
Goc_do = np.degrees(np.arccos(Tich_vo_huong/ (Do_dai_A *Do_dai_B)))
print(Goc_do)

Tích vô hướng của A và B: -8
Do_dai_A
Do_dai_B
108.3755542856849


 C) C^T C

In [11]:
Chuyen_vi_C_nhan_C = C.T @ C
print(Chuyen_vi_C_nhan_C)

[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


Câu 2

In [12]:
M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 1, 0]])
N = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
print("Ma trận M:", M)
print("Ma trận N:", N)

Ma trận M: [[1 2 3 0]
 [4 5 6 1]
 [7 8 9 2]
 [0 1 1 0]]
Ma trận N: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


a) M x N

In [14]:
Tich_M_N = M @ N
print(Tich_M_N)

[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


B) Định thức M

In [13]:
Dinh_thuc_M = np.linalg.det(M)
print(Dinh_thuc_M)

6.66133814775094e-16


C) Hạng của N

In [15]:
Hang_cua_N = np.linalg.matrix_rank(N)
print(Hang_cua_N)

2


CÂU 3

In [18]:
P = np.array([[2, 1, 0, 1], [0, 3, 1, -1], [1, 0, 4, 2], [0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
print(P)
print(b)

[[ 2  1  0  1]
 [ 0  3  1 -1]
 [ 1  0  4  2]
 [ 0  1  0  3]]
[4 7 9 5]


A) Nghịch đảo

In [19]:
Nghich_dao_P = np.linalg.inv(P)
print(Nghich_dao_P)

[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]


B) Giải hệ phương trình

In [20]:
Nghiem_he = np.linalg.solve(P, b)
print(Nghiem_he)

[0.46511628 2.10465116 1.65116279 0.96511628]


C) Kiểm tra nghiệm

In [21]:
Kiem_tra_b = P @ Nghiem_he
print(Kiem_tra_b)

[4. 7. 9. 5.]


CÂU 4

In [22]:
Q = np.array([[4, -1, 0], [1, 3, -2], [0, 1, 2]])
print(Q)
Gia_tri_rieng, Vector_rieng = np.linalg.eig(Q)
print(Gia_tri_rieng)
Vector_rieng_chuan_hoa = Vector_rieng / np.linalg.norm(Vector_rieng, axis=0)
print(Vector_rieng_chuan_hoa)

[[ 4 -1  0]
 [ 1  3 -2]
 [ 0  1  2]]
[3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
[[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743+0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


CÂU 5

In [23]:
R = np.array([[1, -2, 3], [2, 0, 1], [-1, 1, 4]])
print(R)
b2 = np.array([10, 8, 7])
print(b2)

[[ 1 -2  3]
 [ 2  0  1]
 [-1  1  4]]
[10  8  7]


a) Giải Rx = b2

In [24]:
Nghiem_R = np.linalg.solve(R, b2)
print(Nghiem_R)

[2.7826087  0.04347826 2.43478261]


b) Ma trận nghịch đảo và kiểm tra nghiệm

In [25]:
Nghich_dao_R = np.linalg.inv(R)
print(Nghich_dao_R)
Kiem_tra_lai = Nghich_dao_R @ b2
print(Kiem_tra_lai)

[[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
[2.7826087  0.04347826 2.43478261]


c) Chuẩn Frobenius

In [26]:
Chuan_Frobenius = np.linalg.norm(R, 'fro')
print(Chuan_Frobenius)

6.082762530298219
