**Câu 1**

In [3]:
#Ma trận
import numpy as np
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])
print("Ma trận A:", A)
print("Ma trận B:", B)
print("Ma trận C:", C)

Ma trận A: [ 2 -1  3  0]
Ma trận B: [ 1  4 -2  5]
Ma trận C: [[ 1  2 -1]
 [ 0  3  4]
 [ 2 -1  0]]


a) Tính tổng A + B và tích số 2A + 3B. (5 điểm)

In [4]:
tong=A+B
tich=(2*A)+(3*B)
print(tong)
print(tich)

[3 3 1 5]
[ 7 10  0 15]


b) Tính tích vô hướng A · B và góc giữa hai vector (tính bằng độ, làm tròn đến 3 chữ số thập phân).(5 điểm)

In [5]:
Tich_vo_huong = np.dot(A, B)
print("Tích vô hướng của A và B:", Tich_vo_huong)
Do_dai_A = np.linalg.norm(A)
print("Do_dai_A")
Do_dai_B = np.linalg.norm(B)
print("Do_dai_B")
Goc_do = np.degrees(np.arccos(Tich_vo_huong/ (Do_dai_A *Do_dai_B)))
print(Goc_do)

Tích vô hướng của A và B: -8
Do_dai_A
Do_dai_B
108.3755542856849


c) Tính tích ma trận CCT
(ma trận C nhân với chuyển vị của nó). (5 điểm)


In [6]:
Chuyen_vi_C_nhan_C = C.T @ C
print(Chuyen_vi_C_nhan_C)

[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


**Bài 2**

In [8]:
M = np.array([[2, -1, 3, 0], [1, 4, -2, 5], [0, 2, 6, -3], [-1,0, 1, 4]])
N = np.array([[ 1, 3, 2,0], [4, -1, 5, 2], [0,2,3,-1], [-3,1,0,4]])
print("Ma trận M:", M)
print("Ma trận N:", N)

Ma trận M: [[ 2 -1  3  0]
 [ 1  4 -2  5]
 [ 0  2  6 -3]
 [-1  0  1  4]]
Ma trận N: [[ 1  3  2  0]
 [ 4 -1  5  2]
 [ 0  2  3 -1]
 [-3  1  0  4]]


a) Tính tích ma trận M × N. (8 điểm

In [9]:
print(M*N)

[[  2  -3   6   0]
 [  4  -4 -10  10]
 [  0   4  18   3]
 [  3   0   0  16]]


b) Tính định thức của ma trận M. Nếu không khả thi, giải thích lý do. (6 điểm)


In [10]:
Dinh_thuc_M = np.linalg.det(M)
print(Dinh_thuc_M)

409.00000000000017


c) Tính hạng của ma trận N. (6 điểm)

In [11]:
Hang_cua_N = np.linalg.matrix_rank(N)
print(Hang_cua_N)

4


**Câu 3: Nghịch đảo ma trận và giải hệ phương trình (25 điểm)**

In [12]:
P = np.array([[3, -1, 0, 2], [1, 4, -2, -0], [0,1,5,-1], [2,0,1,3]])
print(P)
p = np.array([6, 8, 3, 7])
print(p)

[[ 3 -1  0  2]
 [ 1  4 -2  0]
 [ 0  1  5 -1]
 [ 2  0  1  3]]
[6 8 3 7]


a) Tìm ma trận nghịch đảo của P. Nếu không khả nghịch, giải thích lý do. (10 điểm)

In [13]:
Nghich_dao_P = np.linalg.inv(P)
print(Nghich_dao_P)

[[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]


b) Giải hệ phương trình trên bằng cách sử dụng nghịch đảo ma trận. (10 điểm)


In [17]:
Nghiem_he= np.linalg.solve(P, p)
print(Nghiem_he)

[2.         1.71428571 0.42857143 0.85714286]


c) Kiểm tra nghiệm bằng cách nhân ma trận P với vector nghiệm và so sánh với vector hằng số. (5 điểm)

In [18]:
Kiem_tra_p = P @ Nghiem_he
print(Kiem_tra_p)

[6. 8. 3. 7.]


**Câu 4: Giá trị riêng, vector riêng và chuẩn hóa (20 điểm)**

In [22]:
Q = np.array([[5,-2,1], [ 0, 3,-1], [2,0,4]])
print(Q)

[[ 5 -2  1]
 [ 0  3 -1]
 [ 2  0  4]]


a) Tìm các giá trị riêng của Q. (7 điểm)

In [23]:
Gia_tri_rieng, Vector_rieng = np.linalg.eig(Q)
print(Gia_tri_rieng)

[6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]


b) Tìm các vector riêng tương ứng với các giá trị riêng. (8 điểm)

In [27]:
print(Vector_rieng)

[[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


c)

In [26]:
for i in range(Vector_rieng.shape[1]):
    v = Vector_rieng[:, i]
    v_chuan = v / np.linalg.norm(v)
    print(f"Vector {i+1}:", v_chuan)

Vector 1: [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector 2: [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector 3: [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]


Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích (20 điểm)

In [28]:
R = np.array([[4, -1, 2], [1, 3, -2], [0, 2, 5]])
print(R)
r = np.array([12, 5, 9])
print(r)

[[ 4 -1  2]
 [ 1  3 -2]
 [ 0  2  5]]
[12  5  9]


a) Giải hệ phương trình Rx = b bằng phương pháp np.linalg.solve(). (8 điểm)


In [29]:
Nghiem_R = np.linalg.solve(R, r)
print(Nghiem_R)

[2.78823529 1.52941176 1.18823529]


b) Xác định xem ma trận R có khả nghịch không. Nếu có, tính ma trận nghịch đảo và dùng nó để giải lại hệ. So sánh hai nghiệm. (7 điểm)

In [30]:
Nghich_dao_R = np.linalg.inv(R)
print(Nghich_dao_R)
Kiem_tra_lai = Nghich_dao_R @ r
print(Kiem_tra_lai)

[[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
[2.78823529 1.52941176 1.18823529]


c) Tính chuẩn Frobenius của ma trận R. (5 điểm)

In [31]:
Chuan_Frobenius = np.linalg.norm(R,'fro')
print(Chuan_Frobenius)

8.0
